### ISSUE TITLE
ValueError: could not broadcast input array from shape (1057,389,3) into shape (308,389,3)

### ISSUE THREAD

**Issue by DongLZY** [NVlabs/mask-auto-labeler#16]
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/mask-auto-labeler/datasets/voc.py", line 107, in __getitem__
    data = self.transform(data)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/workspace/mask-auto-labeler/datasets/data_aug.py", line 211, in __call__
    ret_img = custom_crop_image(img, extbox)
  File "/workspace/mask-auto-labeler/datasets/data_aug.py", line 80, in custom_crop_image
    ret_img[-(box[3] - h):, max(-box[0], 0): min(w, box[2]) - box[0]] = img[:box[3] - h, max(0, box[0]):min(w, box[2])]
ValueError: could not broadcast input array from shape (1057,389,3) into shape (308,389,3)

数据增强报错？感觉是因为我的数据集里面图片尺寸不一致造成的。请问有办法解决吗？

**Comment by DongLZY** [comment]
Seems that the size of the pictures in the data set must be the same?

**Comment by voidrank** [comment]
Hi @DongLZY , try to ignore those images or make sure the boxes of objects don't exceed the boundaries
